Update rsa

diff --git a/rsa b/rsa
--- a/rsa
+++ b/rsa
@@ -1,48 +1,27 @@
 #!/usr/bin/env bash
-#is a challenge
-check_factor()
-{
-	if [ $# -ne 3 ];
-        then
-                args=("$@")
-                count=0
-                num2=1
-                for a in ${args[*]};
-                do
-                        if [ $count -gt 1 ];
-                        then
-                                num2=$(echo $a*$num2 | bc)
-                        fi
-                        count=$((count + 1))
-                done
+
+check_factor() {
+    if [ $# -ne 1 ]; then
+        num=$1
+        factors=$(factor "$num")
+        primes=${factors##"$num: "}
+        IFS=' ' read -ra primes_arr <<< "$primes"
+
+        if [ "${#primes_arr[@]}" -eq 2 ]; then
+            echo "$num=${primes_arr[0]}*${primes_arr[1]}"
         else
-                num2=$3
+            echo "Unable to factorize $num"
         fi
-
-        num1=$2
-        num=$(echo "$1" | tr ':' '=')
-
-        result=$(echo "if($num2 > $num1) 1 else 0" | bc)
-	        if ((result == 1)); then
-		        numcp=$num1
-		        num1=$num2
-		        num2=$numcp
-                fi
-
-        echo "$num$num1*$num2"
+    else
+        echo "Unable to factorize $1"
+    fi
 }
 
-if [ $# -ne 1 ]
-then
-        echo 'Usage: rsa <file>'
-        exit 1
+if [ $# -ne 1 ]; then
+    echo 'Usage: rsa <file>'
+    exit 1
 else
-
-        while read i
-        do
-
-                result=$(factor "$i")
-                check_factor $result
-
-        done < "$1"
+    while read -r num; do
+        check_factor "$num"
+    done < "$1"
 fi
